---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    wego.weave.works/app-identifier: wego-46e5d8f9e6eba5e98ea1198f3cda9992
  name: wego-test-app-kgdnq5fv
  namespace: wego-system
spec:
  branch: main
  deployment_type: kustomize
  path: ./
  source_type: git
  url: ssh://git@github.com/weaveworks-gitops-test/wego-test-app-kgdnq5fv.git
